In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("total_emission.csv")
df

,Area,Item,Element,Unit,2000,2001,2002,2003,2004,2005,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,Crop Residues,Direct emissions (N2O),kilotonnes,5.200000e-01,5.267000e-01,8.200000e-01,9.988000e-01,8.225000e-01,1.182100e+00,...,1.032100e+00,1.372600e+00,1.401800e+00,1.458400e+00,1.242400e+00,1.194000e+00,1.061700e+00,8.988000e-01,1.217600e+00,1.317000e+00
1,Afghanistan,Crop Residues,Indirect emissions (N2O),kilotonnes,1.170000e-01,1.185000e-01,1.845000e-01,2.247000e-01,1.851000e-01,2.660000e-01,...,2.322000e-01,3.088000e-01,3.154000e-01,3.281000e-01,2.795000e-01,2.687000e-01,2.389000e-01,2.022000e-01,2.740000e-01,2.963000e-01
2,Afghanistan,Crop Residues,Emissions (N2O),kilotonnes,6.370000e-01,6.452000e-01,1.004500e+00,1.223500e+00,1.007500e+00,1.448100e+00,...,1.264300e+00,1.681500e+00,1.717300e+00,1.786500e+00,1.522000e+00,1.462700e+00,1.300500e+00,1.101100e+00,1.491600e+00,1.613300e+00
3,Afghanistan,Crop Residues,Emissions (CO2eq) from N2O (AR5),kilotonnes,1.688070e+02,1.709884e+02,2.661975e+02,3.242195e+02,2.669995e+02,3.837498e+02,...,3.350379e+02,4.455958e+02,4.550727e+02,4.734174e+02,4.033181e+02,3.876130e+02,3.446447e+02,2.917838e+02,3.952689e+02,4.275284e+02
4,Afghanistan,Crop Residues,Emissions (CO2eq) (AR5),kilotonnes,1.688070e+02,1.709884e+02,2.661975e+02,3.242195e+02,2.669995e+02,3.837498e+02,...,3.350379e+02,4.455958e+02,4.550727e+02,4.734174e+02,4.033181e+02,3.876130e+02,3.446447e+02,2.917838e+02,3.952689e+02,4.275284e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58760,OECD,All sectors without LULUCF,Emissions (CO2),kilotonnes,1.334328e+07,1.326305e+07,1.332979e+07,1.352237e+07,1.366651e+07,1.369481e+07,...,1.289801e+07,1.270146e+07,1.274243e+07,1.261664e+07,1.253301e+07,1.241227e+07,1.243658e+07,1.254684e+07,1.217070e+07,1.088919e+07
58761,OECD,All sectors without LULUCF,Emissions (CO2eq) from F-gases (AR5),kilotonnes,3.941893e+05,3.882647e+05,4.176531e+05,4.392191e+05,4.672796e+05,5.080909e+05,...,7.759070e+05,7.826597e+05,8.006688e+05,8.326775e+05,8.546258e+05,8.741566e+05,8.884415e+05,9.049044e+05,9.172806e+05,9.208261e+05
58762,OECD,All sectors without LULUCF,Emissions (CO2eq) from CH4 (AR5),kilotonnes,2.145052e+06,2.126567e+06,2.093083e+06,2.038232e+06,2.047953e+06,2.008645e+06,...,1.980459e+06,1.971959e+06,1.922551e+06,1.934854e+06,1.924370e+06,1.880327e+06,1.915982e+06,1.923635e+06,1.882769e+06,1.825476e+06
58763,OECD,All sectors without LULUCF,Emissions (CO2eq) from N2O (AR5),kilotonnes,8.535273e+05,8.496131e+05,8.400758e+05,8.124412e+05,8.328157e+05,8.123489e+05,...,8.344119e+05,8.490201e+05,8.204159e+05,8.325680e+05,8.289014e+05,8.218071e+05,8.400423e+05,8.349622e+05,8.118189e+05,8.009744e+05
58764,OECD,All sectors without LULUCF,Emissions (CO2eq) (AR5),kilotonnes,1.673605e+07,1.662750e+07,1.668060e+07,1.681226e+07,1.701456e+07,1.702390e+07,...,1.648879e+07,1.630510e+07,1.628606e+07,1.621674e+07,1.614090e+07,1.598856e+07,1.608104e+07,1.621034e+07,1.578256e+07,1.443647e+07

In [12]:
unique_elm = df['Element'].unique()
unique_elm

array(['Direct emissions (N2O)', 'Indirect emissions (N2O)',
       'Emissions (N2O)', 'Emissions (CO2eq) from N2O (AR5)',
       'Emissions (CO2eq) (AR5)', 'Emissions (CH4)',
       'Emissions (CO2eq) from CH4 (AR5)', 'Emissions (CO2)',
       'Emissions (CO2eq) from F-gases (AR5)'], dtype=object)

In [22]:
elm = [
    'Direct emissions (N2O)', 'Indirect emissions (N2O)',
       'Emissions (N2O)', 'Emissions (CO2eq) from N2O (AR5)',
       'Emissions (CO2eq) (AR5)', 'Emissions (CH4)',
       'Emissions (CO2eq) from CH4 (AR5)', 'Emissions (CO2)',
       'Emissions (CO2eq) from F-gases (AR5)'
    ]

In [45]:
def find_net_amount(year, elm_no):
    year = str(year)
    x = np.sum(df[df['Element'] == elm_no][year])
    return x

In [48]:
find_net_amount(2000, elm[1])

In [47]:
results = []
for i in range(2000, 2021):
    result = {
        'year' : i,
        elm[0] : find_net_amount(i, elm[0]),
        elm[1] : find_net_amount(i, elm[1]),
        elm[2] : find_net_amount(i, elm[2]),
        elm[3] : find_net_amount(i, elm[3]),
        elm[4] : find_net_amount(i, elm[4]),
        elm[5] : find_net_amount(i, elm[5]),
        elm[6] : find_net_amount(i, elm[6]),
        elm[7] : find_net_amount(i, elm[7])
    }
    results.append(result)
results_df = pd.DataFrame(results)
results_df

,year,Direct emissions (N2O),Indirect emissions (N2O),Emissions (N2O),Emissions (CO2eq) from N2O (AR5),Emissions (CO2eq) (AR5),Emissions (CH4),Emissions (CO2eq) from CH4 (AR5),Emissions (CO2)
0,2000,None,None,None,None,None,None,None,None
1,2001,None,None,None,None,None,None,None,None
2,2002,None,None,None,None,None,None,None,None
3,2003,None,None,None,None,None,None,None,None
4,2004,None,None,None,None,None,None,None,None
5,2005,None,None,None,None,None,None,None,None
6,2006,None,None,None,None,None,None,None,None
7,2007,None,None,None,None,None,None,None,None
8,2008,None,None,None,None,None,None,None,None
9,2009,None,None,None,None,None,None,None,None
10,2010,None,None,None,None,None,None,None,None
11,2011,None,None,None,None,None,None,None,None
12,2012,None,None,None,None,None,None,None,None
13,2013,None,None,None,None,None,None,None,None
14,2014,None,None,None,None,None,None,None,None
15,2015,None,None,None,None,None,None,None,None
16,2016,None,None,None,None,None,None,None,None
17,2017,None,None,None,None,None,None,None,None
18,2018,None,None,None,None,None,None,None,None
19,2019,None,None,None,None,None,None,None,None
20,2020,None,None,None,None,None,None,None,None